### PR TITLE
Add wallet abstraction

### PR DESCRIPTION
**Pull request by KingGorrin**
Implementation for feature https://github.com/hypercore-one/znn_sdk_dart/issues/2

Some changes have been introduced since issue https://github.com/hypercore-one/znn_sdk_dart/issues/2

The additional changes include:

- `WalletManager`, `Wallet` and `WalletDefinition` interfaces

These interfaces enable the complete decoupling of the `KeyFile` specific wallet implementation. The same interfaces have been used in the [Zenon SDK for .NET](https://github.com/hypercore-one/znn_sdk_csharp/tree/wallet) library to implement a separate [ledger wallet](https://github.com/hypercore-one/znn_sdk_csharp/tree/ledger) library.

Using the wallet abstraction, the individual wallet libraries can be used in combination with each other, as demonstrated in the ledger implementation of the [Zenon CLI for .NET](https://github.com/hypercore-one/znn_cli_csharp/tree/bigint-ledger).

**Compatibility**

The changes are 98% compatible. Breaking changes include:

- The `address` property of the `KeyPair` class has been replaced by the async `getAddress()` method.
- The `saveKeyStore` method of the `KeyStoreManager` class now returns a `WalletDefinition` instead of a `File` class.

**Future possibilities**

Separate the file based wallet implementation from the main library.

### CODE REVIEW

**Review by vilkris4 — APPROVED** [review]
Looks good to me. These changes were already previously discussed and reviewed in the [hypercore-one repo](https://github.com/hypercore-one/znn_sdk_dart/pull/3).

**Comment by KingGorrin** [comment]
Correct, but some changes and interfaces have been added since the last review in the hc1 repo and I wanted to make sure the latest changes are reviewed before merging them.

**Review by Sol-Sanctum — APPROVED** [review]
The changes look good to me, as well

**Comment by KingGorrin** [comment]
Found a crucial bug in the `KeyStore.signTx` impl. while testing.

**Pull request merged**
